---
title: Slime Crime
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Welcome to the Slime Crime site!
baseurl: ''
username: Slime Crime
typing_text: Game Dev Studio
email: SlimeCrimePrime@gmail.com
twitter_username: Slimecafe
show_aboutme_card: true
about_me_title: Coming Soon
about_me_description: Website under contruction. Feel free to check out our blog posts!
show_skills_card: false
skills_title: Skills
show_timeline_card: false
timeline_title: Education & Experience
cv_download_link: https://example.com/
show_projects_card: true
show_projects: true
projects_title: Our Current Project
show_os_projects: false
os_projects_title: Open Source Projects
show_contact_card: true
contact_title: Contact Us
contact_description: Feel free to get in touch.
repository: SlimeCrimeCafe/slimecrimecafe.github.io
projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true
    projects: 
google-analytics:
  id: ''
plugins:
- jekyll-github-metadata
exclude:
- _assets
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
